# Generated by Django 5.2.17 on 2026-09-02 18:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('question', models.TextField()),
                ('question_normalized', models.TextField()),
                ('question_hash', models.CharField(db_index=True, max_length=64)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('candidate_ids', models.JSONField(blank=True, default=list)),
                ('reranked', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('answered', 'answered'), ('partial', 'partial'), ('not_found', 'not_found'), ('degraded', 'degraded'), ('error', 'error')], max_length=16)),
                ('models_used', models.JSONField(blank=True, default=dict)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('latency_ms', models.JSONField(blank=True, default=dict)),
                ('cache_hit', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('feedback', models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=4)),
                ('feedback_note', models.CharField(blank=True, max_length=1000)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='smartquery_status_created_idx')],
            },
        ),
    ]
