# Generated by Django 5.2.17 on 2026-09-02 18:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_remove_chunk_embedding'),
        ('search', '0001_smartquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ayah_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ayah_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('chunk_idx_start', models.PositiveIntegerField()),
                ('chunk_idx_end', models.PositiveIntegerField()),
                ('start_ms', models.PositiveBigIntegerField()),
                ('end_ms', models.PositiveBigIntegerField()),
                ('word_count', models.PositiveIntegerField()),
                ('header', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('text_normalized', models.TextField()),
                ('text_stem', models.TextField()),
                ('tsv', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('text_stem', config='simple'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('embedded_hash', models.CharField(blank=True, max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='corpus.segment')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='corpus.transcript')),
            ],
            options={
                'ordering': ['transcript_id', 'ordinal'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tsv'], name='passage_tsv_gin'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='passage_embedding_hnsw', opclasses=['halfvec_cosine_ops']), models.Index(fields=['segment', 'ordinal'], name='passage_segment_ordinal_idx'), models.Index(fields=['surah', 'ayah_start'], name='passage_surah_ayah_idx')],
                'constraints': [models.UniqueConstraint(fields=('transcript', 'ordinal'), name='passage_unique_transcript_ordinal')],
            },
        ),
    ]
