/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ayahs/{surah}/{ayah}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/ayahs/{surah}/{ayah}/`` — the verse and the segments whose
         *     declared ayah range covers it. A segment with no range covers nothing.
         */
        get: operations["ayah_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ``POST /api/clips/`` — enqueue a render, or hand back the one that is
         *     already running.
         *
         *     The (segment, range, preset) tuple is unique, which makes the job table its
         *     own cache: the second person to share the same passage joins the first
         *     person's render instead of starting another. ``202`` means "queued by you",
         *     ``200`` means "already queued".
         *
         *     The one job that is *not* simply handed back is a failed one: asking for it
         *     again queues one more attempt on the same row, so a transient worker or
         *     storage failure is not a clip nobody can ever have.
         */
        post: operations["clip_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/clips/{id}/`` — poll a job. Never cached: status moves. */
        get: operations["clips_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corrections/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ``POST /api/corrections/`` — anonymous, IP-throttled suggestion inbox.
         *
         *     Nothing here touches the transcript: a correction is reviewed and applied
         *     by a human later (Phase 6). The response is a bare receipt so a submitter
         *     cannot use the endpoint to enumerate the queue.
         */
        post: operations["correction_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/search/?q=&kind=&surah=&page=`` (API_CONTRACT.md).
         *
         *     Never cached: results move with every pipeline run.
         */
        get: operations["search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/suggest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/search/suggest/?q=`` — autocomplete suggestions.
         *
         *     Returns a plain list of strings (matched chunk text snippets).
         *     Never cached; results move with every pipeline run.
         */
        get: operations["search_suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/segments/{id}/`` — metadata plus presigned media URLs.
         *
         *     Not immutable, despite the rest of the segment being append-only: the body
         *     embeds presigned audio and waveform URLs that expire in six hours, so it is
         *     ``private`` (a shared cache must not hand one reader's signed URL to
         *     another) and short-lived (API_CONTRACT.md amendment 4).
         */
        get: operations["segments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{id}/chunks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/segments/{id}/chunks/`` — passage spans and their word ranges.
         *
         *     The client already has the word array from ``/transcript/``; this says
         *     which passage each word belongs to, which is what a correction has to name
         *     when it is submitted. Short-lived cache, NOT immutable: the URL carries no
         *     transcript version, and an approved correction can renumber word indices —
         *     a year-old chunk map would target the wrong words.
         *
         *     Assembled from two ``values_list`` queries rather than through the
         *     serializer, for the reason ``SegmentTranscriptView`` gives — the payload is
         *     mechanical and a transcript can carry thousands of words.
         */
        get: operations["segment_chunks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{id}/transcript/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/segments/{id}/transcript/`` — the whole word array.
         *
         *     Content-addressed by ``Transcript.version``: an approved correction bumps
         *     the version, so the client asks for a new ``?v=`` rather than revalidating.
         */
        get: operations["segment_transcript_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surahs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/surahs/`` — all 114, unpaginated, with segment counts. */
        get: operations["surahs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surahs/{number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/surahs/{n}/?page=`` — the surah plus one page of ayahs. */
        get: operations["surah_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/topics/`` — the published topics only.
         *
         *     An unpublished topic is an unreviewed cluster label, so it is invisible
         *     rather than merely unlinked: nothing about it leaves the backend. Which is
         *     also why this is not immutable: publishing is an editorial decision, and an
         *     immutable response would mean unpublishing never reaches anyone who already
         *     looked (API_CONTRACT.md amendment 4).
         */
        get: operations["topics_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/topics/{slug}/`` — the topic and its best passages.
         *
         *     Cached like the list for the same reason: the publish gate has to be able
         *     to close again.
         */
        get: operations["topic_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ``GET /api/ayahs/{surah}/{ayah}/`` — the verse and what covers it. */
        AyahDetail: {
            surah: number;
            number: number;
            text_uthmani: string;
            text_imlaei: string;
            juz: number;
            /** @description Madani mushaf page, 1-604. */
            page: number;
            readonly segments: components["schemas"]["CoveringSegment"][];
        };
        /** @description An exact verse resolved from the query itself, shown above the hits. */
        AyahMatch: {
            surah: number;
            number: number;
            text_uthmani: string;
            surah_name_ar: string;
        };
        /** @description The ``ayahs`` envelope: a fixed-size page, not a DRF paginator shape. */
        AyahPage: {
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["SurahAyah"][];
        };
        /**
         * @description A covering segment as listed on a surah page — just enough to link to it.
         *
         *     Serialized from the ``.values()`` dicts the view fans out, not from model
         *     instances, so the whole page costs one segment query.
         */
        AyahSegmentRef: {
            readonly id: number;
            readonly kind: components["schemas"]["KindEnum"];
            readonly title: string;
        };
        /**
         * @description The search-result shape, reused wherever chunks are surfaced (topics)
         *     so one renderer on the frontend handles all of them.
         *     Mirrors :class:`search.services.SearchResult`.
         */
        ChunkResult: {
            chunk_id: number;
            segment_id: number;
            segment_title: string;
            surah: number | null;
            ayah_start: number | null;
            ayah_end: number | null;
            kind: string;
            text: string;
            start_ms: number;
            end_ms: number;
        };
        /**
         * @description One row of ``GET /api/segments/{id}/chunks/``.
         *
         *     The map from a word to the passage that holds it: the correction UI lets a
         *     reader select words in the transcript and has to name a ``chunk_id`` when
         *     it posts, so it needs the chunks' word ranges. ``word_start``/``word_end``
         *     are inclusive ``TranscriptWord.idx`` values — the same transcript-wide
         *     indices ``POST /api/corrections/`` takes — and are null only for a chunk
         *     whose span holds no aligned words.
         */
        ChunkSpan: {
            chunk_id: number;
            start_ms: number;
            end_ms: number;
            word_start: number | null;
            word_end: number | null;
        };
        /**
         * @description ``POST /api/clips/``. Rendering is somebody's CPU, so the range is
         *     checked against the segment before a job is ever created.
         */
        ClipCreateRequest: {
            segment_id: number;
            /** Format: int64 */
            start_ms: number;
            /** Format: int64 */
            end_ms: number;
            preset: components["schemas"]["PresetEnum"];
            output?: components["schemas"]["ClipOutputEnum"];
        };
        /**
         * @description ``GET /api/clips/{id}/``. Exactly one of ``video_url``/``audio_url``
         * appears once the render finishes; a queued or failed job has neither.
         */
        ClipDetail: {
            /** Format: uuid */
            readonly id: string;
            status?: components["schemas"]["ClipStatusEnum"];
            output?: components["schemas"]["ClipOutputEnum"];
            /** Format: uri */
            readonly video_url: string | null;
            /** Format: uri */
            readonly audio_url: string | null;
        };
        /** @description The body of both clip POST outcomes: created, or already queued. */
        ClipStatus: {
            /** Format: uuid */
            readonly id: string;
            status?: components["schemas"]["ClipStatusEnum"];
        };
        /**
         * @description * `queued` - Queued
         *     * `rendering` - Rendering
         *     * `done` - Done
         *     * `failed` - Failed
         * @enum {string}
         */
        ClipStatusEnum: "queued" | "rendering" | "done" | "failed";
        /**
         * @description * `video` - Video
         *     * `audio` - Audio
         * @enum {string}
         */
        ClipOutputEnum: "video" | "audio";
        /**
         * @description ``POST /api/corrections/``. Word offsets index ``TranscriptWord.idx``;
         *     a one-word fix has ``word_start == word_end``.
         *
         *     The range is checked against the named chunk's own words here, not only at
         *     approval time. :func:`corpus.corrections.approve` refuses a range that
         *     reaches outside its chunk, so accepting one at submission would queue a
         *     suggestion that no reviewer can ever act on: a dead letter that costs the
         *     submitter their rate limit and the reviewer a decision they cannot make.
         */
        CorrectionCreateRequest: {
            chunk_id: number;
            word_start: number;
            word_end: number;
            suggested_text: string;
        };
        /** @description The 201 body: a receipt, nothing the submitter did not already send. */
        CorrectionCreated: {
            readonly id: number;
            status?: components["schemas"]["CorrectionStatusEnum"];
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        CorrectionStatusEnum: "pending" | "approved" | "rejected";
        /** @description A segment listed under an ayah it covers. */
        CoveringSegment: {
            readonly id: number;
            kind: components["schemas"]["KindEnum"];
            title?: string;
            ayah_start?: number | null;
            ayah_end?: number | null;
            /** Format: int64 */
            duration_ms: number;
        };
        /** @description The shape every 4xx in this API uses. */
        Error: {
            detail: string;
        };
        /**
         * @description * `recitation` - Recitation
         *     * `khawatir` - Khawatir
         * @enum {string}
         */
        KindEnum: "recitation" | "khawatir";
        /**
         * @description * `classic` - Classic
         *     * `night` - Night
         *     * `light` - Light
         * @enum {string}
         */
        PresetEnum: "classic" | "night" | "light";
        /**
         * @description * `makkah` - Makkah
         *     * `madinah` - Madinah
         * @enum {string}
         */
        RevelationPlaceEnum: "makkah" | "madinah";
        /** @description ``GET /api/search/`` — mirrors :class:`search.services.SearchResponse`. */
        SearchResponse: {
            query: string;
            ayah_matches: components["schemas"]["AyahMatch"][];
            verse_matches: components["schemas"]["VerseMatch"][];
            results: components["schemas"]["ChunkResult"][];
            page: number;
            total: number;
        };
        /**
         * @description ``GET /api/segments/{id}/``. Requires ``select_related`` on ``audio``,
         *     ``source`` and ``transcript``.
         */
        SegmentDetail: {
            readonly id: number;
            kind: components["schemas"]["KindEnum"];
            title?: string;
            surah: number | null;
            ayah_start?: number | null;
            ayah_end?: number | null;
            /** Format: int64 */
            duration_ms: number;
            ordinal?: number;
            /** Format: uri */
            readonly audio_url: string;
            /** Format: uri */
            readonly waveform_url: string;
            readonly source: components["schemas"]["SourceBrief"];
            readonly transcript_version: number | null;
            readonly is_human_reviewed: boolean;
        };
        /** @description Provenance line shown next to a segment. */
        SourceBrief: {
            title: string;
            kind: string;
        };
        /**
         * @description One ayah inside a paginated surah page.
         *
         *     ``segments`` is capped at ``views.MAX_AYAH_SEGMENTS``; ``segment_count`` is
         *     the uncapped total.
         */
        SurahAyah: {
            number: number;
            text_uthmani: string;
            juz: number;
            /** @description Madani mushaf page, 1-604. */
            page: number;
            sajda?: boolean;
            readonly segment_count: number;
            readonly segments: components["schemas"]["AyahSegmentRef"][];
        };
        /** @description ``GET /api/surahs/{n}/`` — surah head plus one page of its ayahs. */
        SurahDetail: {
            number: number;
            name_ar: string;
            name_en: string;
            ayah_count: number;
            revelation_place: components["schemas"]["RevelationPlaceEnum"];
            ayahs: components["schemas"]["AyahPage"];
        };
        /** @description One row of ``GET /api/surahs/``. */
        SurahList: {
            number: number;
            name_ar: string;
            /** @description name_ar passed through corpus.arabic.normalize_for_index. */
            name_ar_plain: string;
            name_en: string;
            ayah_count: number;
            revelation_place: components["schemas"]["RevelationPlaceEnum"];
            readonly segment_count: number;
        };
        /**
         * @description ``GET /api/topics/{slug}/``. The view attaches ``chunks`` — the topic's
         *     passages, best match first — before serialization.
         */
        TopicDetail: {
            slug: string;
            name_ar: string;
            description_ar?: string;
            readonly chunk_count: number;
            readonly chunks: components["schemas"]["ChunkResult"][];
        };
        /** @description One row of ``GET /api/topics/``. */
        TopicList: {
            slug: string;
            name_ar: string;
            description_ar?: string;
            readonly chunk_count: number;
        };
        /**
         * @description ``GET /api/segments/{id}/transcript/``.
         *
         *     Declared for the schema only: the view assembles the word list straight
         *     from ``values_list`` because running six thousand rows through a serializer
         *     per request is pure overhead for a payload this mechanical.
         */
        Transcript: {
            version: number;
            engine: string;
            is_human_reviewed: boolean;
            words: components["schemas"]["TranscriptWord"][];
        };
        /** @description ``i`` index, ``t`` text, ``s``/``e`` start/end ms, ``c`` confidence. */
        TranscriptWord: {
            i: number;
            t: string;
            s: number;
            e: number;
            /** Format: double */
            c: number | null;
        };
        /** @description A mushaf verse found by full-text search over the canonical text. */
        VerseMatch: {
            surah: number;
            number: number;
            text_uthmani: string;
            surah_name_ar: string;
            juz: number;
            page: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ayah_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ayah: number;
                surah: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahDetail"];
                };
            };
        };
    };
    clip_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClipCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ClipCreateRequest"];
                "multipart/form-data": components["schemas"]["ClipCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipStatus"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipStatus"];
                };
            };
        };
    };
    clips_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipDetail"];
                };
            };
        };
    };
    correction_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CorrectionCreateRequest"];
                "multipart/form-data": components["schemas"]["CorrectionCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionCreated"];
                };
            };
        };
    };
    search_retrieve: {
        parameters: {
            query: {
                kind?: string;
                page?: number;
                q: string;
                surah?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    search_suggest: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    segments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentDetail"];
                };
            };
        };
    };
    segment_chunks_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkSpan"][];
                };
            };
        };
    };
    segment_transcript_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
        };
    };
    surahs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurahList"][];
                };
            };
        };
    };
    surah_retrieve: {
        parameters: {
            query?: {
                /** @description 1-based, 20 ayahs per page. */
                page?: number;
            };
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurahDetail"];
                };
            };
        };
    };
    topics_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"][];
                };
            };
        };
    };
    topic_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
        };
    };
}
