/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ayahs/{surah}/{ayah}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/ayahs/{surah}/{ayah}/`` — the verse and the segments whose
         *     declared ayah range covers it. A segment with no range covers nothing.
         */
        get: operations["ayah_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ``POST /api/clips/`` — enqueue a render, or hand back the one that is
         *     already running.
         *
         *     The (segment, range, preset) tuple is unique, which makes the job table its
         *     own cache: the second person to share the same passage joins the first
         *     person's render instead of starting another. ``202`` means "queued by you",
         *     ``200`` means "already queued".
         */
        post: operations["clip_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/clips/{id}/`` — poll a job. Never cached: status moves. */
        get: operations["clips_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corrections/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ``POST /api/corrections/`` — anonymous, IP-throttled suggestion inbox.
         *
         *     Nothing here touches the transcript: a correction is reviewed and applied
         *     by a human later (Phase 6). The response is a bare receipt so a submitter
         *     cannot use the endpoint to enumerate the queue.
         */
        post: operations["correction_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/search/?q=&mode=&kind=&surah=&page=`` (API_CONTRACT.md).
         *
         *     Never cached: results move with every pipeline run.
         */
        get: operations["search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/segments/{id}/`` — metadata plus presigned media URLs. */
        get: operations["segments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{id}/related/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/segments/{id}/related/`` — nearest passages elsewhere.
         *
         *     The segment is reduced to the centroid of its chunk embeddings, and the
         *     corpus is searched by cosine distance to that centroid with the segment's
         *     own chunks excluded. Cosine distance ignores magnitude, so the mean needs
         *     no renormalization. A segment that has not been embedded yet returns ``[]``
         *     rather than an error — embedding lags ingestion.
         */
        get: operations["segment_related_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{id}/transcript/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/segments/{id}/transcript/`` — the whole word array.
         *
         *     Content-addressed by ``Transcript.version``: an approved correction bumps
         *     the version, so the client asks for a new ``?v=`` rather than revalidating.
         */
        get: operations["segment_transcript_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surahs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/surahs/`` — all 114, unpaginated, with segment counts. */
        get: operations["surahs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surahs/{number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/surahs/{n}/?page=`` — the surah plus one page of ayahs. */
        get: operations["surah_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/topics/`` — the published topics only.
         *
         *     An unpublished topic is an unreviewed cluster label, so it is invisible
         *     rather than merely unlinked: nothing about it leaves the backend.
         */
        get: operations["topics_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/topics/{slug}/`` — the topic and its passages, best first. */
        get: operations["topic_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ``GET /api/ayahs/{surah}/{ayah}/`` — the verse and what covers it. */
        AyahDetail: {
            surah: number;
            /** Format: int64 */
            number: number;
            text_uthmani: string;
            text_imlaei: string;
            /** Format: int64 */
            juz: number;
            /**
             * Format: int64
             * @description Madani mushaf page, 1-604.
             */
            page: number;
            readonly segments: components["schemas"]["CoveringSegment"][];
        };
        /** @description An exact verse resolved from the query itself, shown above the hits. */
        AyahMatch: {
            surah: number;
            number: number;
            text_uthmani: string;
            surah_name_ar: string;
        };
        /** @description The ``ayahs`` envelope: a fixed-size page, not a DRF paginator shape. */
        AyahPage: {
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["SurahAyah"][];
        };
        /**
         * @description The search-result shape, reused wherever chunks are surfaced (topics,
         *     related passages) so one renderer on the frontend handles all of them.
         *     Mirrors :class:`search.services.SearchResult`.
         */
        ChunkResult: {
            chunk_id: number;
            segment_id: number;
            segment_title: string;
            surah: number | null;
            ayah_start: number | null;
            ayah_end: number | null;
            kind: string;
            text: string;
            start_ms: number;
            end_ms: number;
        };
        /**
         * @description ``POST /api/clips/``. Rendering is somebody's CPU, so the range is
         *     checked against the segment before a job is ever created.
         */
        ClipCreateRequest: {
            segment_id: number;
            /** Format: int64 */
            start_ms: number;
            /** Format: int64 */
            end_ms: number;
            preset: components["schemas"]["PresetEnum"];
        };
        /**
         * @description ``GET /api/clips/{id}/``. ``video_url`` appears only once the render
         *     finished — a queued or failed job has nothing to hand out.
         */
        ClipDetail: {
            /** Format: uuid */
            readonly id: string;
            status?: components["schemas"]["ClipStatusEnum"];
            /** Format: uri */
            readonly video_url: string | null;
        };
        /** @description The body of both clip POST outcomes: created, or already queued. */
        ClipStatus: {
            /** Format: uuid */
            readonly id: string;
            status?: components["schemas"]["ClipStatusEnum"];
        };
        /**
         * @description * `queued` - Queued
         *     * `rendering` - Rendering
         *     * `done` - Done
         *     * `failed` - Failed
         * @enum {string}
         */
        ClipStatusEnum: "queued" | "rendering" | "done" | "failed";
        /**
         * @description ``POST /api/corrections/``. Word offsets index ``TranscriptWord.idx``;
         *     a one-word fix has ``word_start == word_end``.
         */
        CorrectionCreateRequest: {
            chunk_id: number;
            /** Format: int64 */
            word_start: number;
            /** Format: int64 */
            word_end: number;
            suggested_text: string;
        };
        /** @description The 201 body: a receipt, nothing the submitter did not already send. */
        CorrectionCreated: {
            readonly id: number;
            status?: components["schemas"]["CorrectionStatusEnum"];
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        CorrectionStatusEnum: "pending" | "approved" | "rejected";
        /** @description A segment listed under an ayah it covers. */
        CoveringSegment: {
            readonly id: number;
            kind: components["schemas"]["KindEnum"];
            title?: string;
            /** Format: int64 */
            ayah_start?: number | null;
            /** Format: int64 */
            ayah_end?: number | null;
            /** Format: int64 */
            duration_ms: number;
        };
        /** @description The shape every 4xx in this API uses. */
        Error: {
            detail: string;
        };
        /**
         * @description * `recitation` - Recitation
         *     * `khawatir` - Khawatir
         * @enum {string}
         */
        KindEnum: "recitation" | "khawatir";
        /**
         * @description * `lexical` - lexical
         *     * `semantic` - semantic
         *     * `hybrid` - hybrid
         * @enum {string}
         */
        ModeEnum: "lexical" | "semantic" | "hybrid";
        /**
         * @description * `classic` - Classic
         *     * `night` - Night
         *     * `light` - Light
         * @enum {string}
         */
        PresetEnum: "classic" | "night" | "light";
        /**
         * @description * `makkah` - Makkah
         *     * `madinah` - Madinah
         * @enum {string}
         */
        RevelationPlaceEnum: "makkah" | "madinah";
        /** @description ``GET /api/search/`` — mirrors :class:`search.services.SearchResponse`. */
        SearchResponse: {
            query: string;
            mode: components["schemas"]["ModeEnum"];
            ayah_matches: components["schemas"]["AyahMatch"][];
            results: components["schemas"]["ChunkResult"][];
            page: number;
            total: number;
        };
        /**
         * @description ``GET /api/segments/{id}/``. Requires ``select_related`` on ``audio``,
         *     ``source`` and ``transcript``.
         */
        SegmentDetail: {
            readonly id: number;
            kind: components["schemas"]["KindEnum"];
            title?: string;
            surah: number | null;
            /** Format: int64 */
            ayah_start?: number | null;
            /** Format: int64 */
            ayah_end?: number | null;
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            ordinal?: number;
            /** Format: uri */
            readonly audio_url: string;
            /** Format: uri */
            readonly waveform_url: string;
            readonly source: components["schemas"]["SourceBrief"];
            readonly transcript_version: number | null;
            readonly is_human_reviewed: boolean;
        };
        /** @description Provenance line shown next to a segment. */
        SourceBrief: {
            title: string;
            kind: string;
        };
        /** @description One ayah inside a paginated surah page. */
        SurahAyah: {
            /** Format: int64 */
            number: number;
            text_uthmani: string;
            /** Format: int64 */
            juz: number;
            /**
             * Format: int64
             * @description Madani mushaf page, 1-604.
             */
            page: number;
            sajda?: boolean;
            readonly segment_count: number;
        };
        /** @description ``GET /api/surahs/{n}/`` — surah head plus one page of its ayahs. */
        SurahDetail: {
            number: number;
            name_ar: string;
            name_en: string;
            ayah_count: number;
            revelation_place: components["schemas"]["RevelationPlaceEnum"];
            ayahs: components["schemas"]["AyahPage"];
        };
        /** @description One row of ``GET /api/surahs/``. */
        SurahList: {
            /** Format: int64 */
            number: number;
            name_ar: string;
            /** @description name_ar passed through corpus.arabic.normalize_for_index. */
            name_ar_plain: string;
            name_en: string;
            /** Format: int64 */
            ayah_count: number;
            revelation_place: components["schemas"]["RevelationPlaceEnum"];
            readonly segment_count: number;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        /**
         * @description ``GET /api/topics/{slug}/``. The view attaches ``chunks`` — the topic's
         *     passages, best match first — before serialization.
         */
        TopicDetail: {
            slug: string;
            name_ar: string;
            description_ar?: string;
            readonly chunk_count: number;
            readonly chunks: components["schemas"]["ChunkResult"][];
        };
        /** @description One row of ``GET /api/topics/``. */
        TopicList: {
            slug: string;
            name_ar: string;
            description_ar?: string;
            readonly chunk_count: number;
        };
        /**
         * @description ``GET /api/segments/{id}/transcript/``.
         *
         *     Declared for the schema only: the view assembles the word list straight
         *     from ``values_list`` because running six thousand rows through a serializer
         *     per request is pure overhead for a payload this mechanical.
         */
        Transcript: {
            version: number;
            engine: string;
            is_human_reviewed: boolean;
            words: components["schemas"]["TranscriptWord"][];
        };
        /** @description ``i`` index, ``t`` text, ``s``/``e`` start/end ms, ``c`` confidence. */
        TranscriptWord: {
            i: number;
            t: string;
            s: number;
            e: number;
            /** Format: double */
            c: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ayah_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ayah: number;
                surah: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahDetail"];
                };
            };
        };
    };
    clip_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClipCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ClipCreateRequest"];
                "multipart/form-data": components["schemas"]["ClipCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipStatus"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipStatus"];
                };
            };
        };
    };
    clips_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipDetail"];
                };
            };
        };
    };
    correction_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CorrectionCreateRequest"];
                "multipart/form-data": components["schemas"]["CorrectionCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionCreated"];
                };
            };
        };
    };
    search_retrieve: {
        parameters: {
            query: {
                kind?: string;
                mode?: "hybrid" | "lexical" | "semantic";
                page?: number;
                q: string;
                surah?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    segments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentDetail"];
                };
            };
        };
    };
    segment_related_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkResult"][];
                };
            };
        };
    };
    segment_transcript_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
        };
    };
    surahs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurahList"][];
                };
            };
        };
    };
    surah_retrieve: {
        parameters: {
            query?: {
                /** @description 1-based, 20 ayahs per page. */
                page?: number;
            };
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurahDetail"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    topics_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"][];
                };
            };
        };
    };
    topic_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
        };
    };
}
