# Generated by Django 5.2.17 on 2026-08-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_ar_plain', models.CharField(help_text='name_ar passed through corpus.arabic.normalize_for_index.', max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('ayah_count', models.PositiveSmallIntegerField()),
                ('revelation_place', models.CharField(choices=[('makkah', 'Makkah'), ('madinah', 'Madinah')], max_length=8)),
                ('order_revealed', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'surah',
                'verbose_name_plural': 'surahs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('text_uthmani', models.TextField()),
                ('text_imlaei', models.TextField()),
                ('text_normalized', models.TextField(help_text='text_uthmani passed through corpus.arabic.normalize_for_index.')),
                ('juz', models.PositiveSmallIntegerField()),
                ('hizb', models.PositiveSmallIntegerField(help_text='Hizb quarter, 1-240.')),
                ('page', models.PositiveSmallIntegerField(help_text='Madani mushaf page, 1-604.')),
                ('sajda', models.BooleanField(default=False)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah')),
            ],
            options={
                'verbose_name': 'ayah',
                'verbose_name_plural': 'ayahs',
                'ordering': ['surah_id', 'number'],
                'indexes': [models.Index(fields=['surah', 'number'], name='ayah_surah_number_idx')],
                'constraints': [models.UniqueConstraint(fields=('surah', 'number'), name='ayah_unique_surah_number')],
            },
        ),
    ]
