# Generated by Django 5.2.17 on 2026-08-18 11:19

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        # CREATE EXTENSION vector -- must precede any VectorField column.
        VectorExtension(),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500)),
                ('duration_ms', models.PositiveBigIntegerField()),
                ('mime', models.CharField(max_length=100)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['storage_key'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('rights_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recitation', 'Recitation'), ('khawatir', 'Khawatir')], max_length=16)),
                ('ayah_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ayah_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveBigIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribed', 'Transcribed'), ('aligned', 'Aligned'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='corpus.audioasset')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='quran.surah')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='corpus.source')),
            ],
            options={
                'ordering': ['source_id', 'ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('detail', models.TextField(blank=True, help_text='Free text or traceback.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='corpus.segment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100)),
                ('engine_version', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='ar', max_length=16)),
                ('raw_text', models.TextField()),
                ('text_normalized', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_human_reviewed', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='corpus.segment')),
            ],
            options={
                'ordering': ['segment_id'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_normalized', models.TextField()),
                ('start_ms', models.PositiveBigIntegerField()),
                ('end_ms', models.PositiveBigIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='corpus.transcript')),
            ],
            options={
                'ordering': ['transcript_id', 'idx'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=100)),
                ('start_ms', models.PositiveBigIntegerField()),
                ('end_ms', models.PositiveBigIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='corpus.transcript')),
            ],
            options={
                'ordering': ['transcript_id', 'idx'],
            },
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['surah', 'ayah_start'], name='segment_surah_ayah_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['transcript', 'idx'], name='chunk_transcript_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('transcript', 'idx'), name='chunk_unique_transcript_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptword',
            index=models.Index(fields=['transcript', 'start_ms'], name='tw_transcript_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptword',
            constraint=models.UniqueConstraint(fields=('transcript', 'idx'), name='transcriptword_unique_transcript_idx'),
        ),
    ]
