# Generated by Django 5.2.17 on 2026-08-18 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_start', models.PositiveIntegerField()),
                ('word_end', models.PositiveIntegerField()),
                ('suggested_text', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='corpus.chunk')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='correction_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='corpus.chunk')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_links', to='corpus.topic')),
            ],
            options={
                'ordering': ['topic_id', '-score'],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'topic'), name='chunktopic_unique_chunk_topic')],
            },
        ),
    ]
