# Generated by Django 5.2.17 on 2026-08-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_topic_correction_chunktopic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chunk',
            name='chunk_embedding_hnsw',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='embedding',
        ),
    ]
