# Generated by Django 5.2.17 on 2026-08-18 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0002_topic_correction_chunktopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_ms', models.PositiveBigIntegerField()),
                ('end_ms', models.PositiveBigIntegerField()),
                ('preset', models.CharField(choices=[('classic', 'Classic'), ('night', 'Night'), ('light', 'Light')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='corpus.segment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('segment', 'start_ms', 'end_ms', 'preset'), name='clip_unique_render')],
            },
        ),
    ]
