# Generated by Django 5.2.17 on 2026-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
        ('corpus', '0003_remove_chunk_embedding'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clip',
            name='clip_unique_render',
        ),
        migrations.AddField(
            model_name='clip',
            name='output',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('segment', 'start_ms', 'end_ms', 'preset', 'output'), name='clip_unique_render'),
        ),
    ]
